#!/bin/bash

if [ $# -eq 1 ]
then
    flake8 $1
    echo ""
    pylint $1
    exit 0
fi

list=(`find . -name '*.py'`)
if [ ${#list[@]} -eq 0 ]
then
    echo "* No files found."
    exit 0
fi

echo ""
echo "    #####  #       ###   #   #  #####                           "
echo "    #      #      #   #  # #    #             #####             "
echo "    ####   #      #####  ##     #####         #   #             "
echo "    #      #      #   #  # #    #             #####             "
echo "    #      #      #   #  #  #   #             #   #             "
echo "    #      #####  #   #  #   #  #####         #####             "
echo ""

find . -name '*.py' | xargs flake8

echo ""
echo "    ####   #   #  #       ###   #   #  #####                    "
echo "    #   #  #   #  #        #    ##  #    #                      "
echo "    #   #  #   #  #        #    # # #    #                      "
echo "    ####    ####  #        #    # # #    #                      "
echo "    #          #  #        #    #  ##    #                      "
echo "    #      ####   #####   ###   #   #    #                      "
echo ""

find . -name '*.py' | xargs pylint
