#!/bin/bash

if [ $# -eq 1 ]
then
    sed -i -r 's/ *$//g' $1
    echo "* Successfully deleted trailing-whitespaces in "\"$1\"
    exit 0
fi

list=(`find . -name '*.py'`)
if [ ${#list[@]} -eq 0 ]
then
    echo "* No files found."
    exit 0
fi

echo "* Files to fix:"
for file in "${list[@]}"
do
    echo "  $file"
done

echo -n "* Is it okay? ('y' to continue) "
read confirmation
if [ "$confirmation" = "y" ]
then
    find . -name '*.py' -exec sed -i -r 's/ *$//g' {} \;
    echo "* Successfully deleted trailing-whitespaces in .py files from this directory."
else
    echo "* Cancelled."
fi
